// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPCWrJypZwKbfuIdxsvxzyciapGvKR2I',
    appId: '1:819255818920:web:67b88a8351cda19afba09d',
    messagingSenderId: '819255818920',
    projectId: 'taskify-18564',
    authDomain: 'taskify-18564.firebaseapp.com',
    storageBucket: 'taskify-18564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBe8KP2t3h9PTJLtF--zylvQNmdIjJqgw',
    appId: '1:819255818920:android:28c1624f2a6e4c37fba09d',
    messagingSenderId: '819255818920',
    projectId: 'taskify-18564',
    storageBucket: 'taskify-18564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOwx1494nnSwVfU_6TjnEoA5wbF7rJK4',
    appId: '1:819255818920:ios:6a56bb973e65168cfba09d',
    messagingSenderId: '819255818920',
    projectId: 'taskify-18564',
    storageBucket: 'taskify-18564.appspot.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOwx1494nnSwVfU_6TjnEoA5wbF7rJK4',
    appId: '1:819255818920:ios:e10ae374860118dbfba09d',
    messagingSenderId: '819255818920',
    projectId: 'taskify-18564',
    storageBucket: 'taskify-18564.appspot.com',
    iosBundleId: 'com.example.taskify.RunnerTests',
  );
}
